# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 141a084245d620c8249c0e3e9b124c516d694c9875baa74dfb1f5688db51247d1c87cde39a3d4b2eb69c98f95b95d68d2825f215ba13d1ca23a2c5f97f888584

test:
  secret_key_base: 2366ede9932a132bb6c9e25530083e4682c73c89aa0c352d7e9b36c781f295b3420deceb344fcf9bf5ffe3785c92107c6e215b150ed7bd1bb697794e27220cd1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
